### ISSUE TITLE
.filter alternative

### ISSUE THREAD

**Issue by DigitalPhoneme** [mike-gustafson/js-objects-lab#1]
https://github.com/mike-gustafson/js-objects-lab/blob/5c745045ac20b1cd05fcb9269b809714666df47e/app.js#L45

Your logic for selecting a starter Pokémon works well by filtering for starters and adding a random one to the party. However, using ```Array.filter()``` on ```pokemon``` to create the ```starters``` array could replace the ```forEach``` loop here for brevity:

```
const starters = pokemon.filter(pokemon => pokemon.starter);
game.party.push(starters[Math.floor(Math.random() * starters.length)]);
```

**Comment by mike-gustafson** [comment]
Thanks for the advice.  It makes a lot of sense to use filter in this case.
